FROM java:8
VOLUME /tmp
ADD springboot-demo.jar app.jar
EXPOSE 8089
RUN sh -c 'touch /app.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]